---
- hosts: webserver
  user: root
  tasks:
    - name: Descargamos el tar.gz de drupal8.0.6
      command: wget https://www.drupal.org/files/projects/drupal-8.0.6.tar.gz
    - name: Descomprimimos el paquete
      command: tar -zxvf drupal-8.0.6.tar.gz
    - name: Creamos el directorio /var/www/drupal para almacenar el sitio
      shell: mkdir /var/www/drupal
    - name: Movemos todo a /var/www/drupal
      shell: mv drupal-8.0.6/* drupal-8.0.6/.htaccess drupal-8.0.6/.csslintrc drupal-8.0.6/.editorconfig drupal-8.0.6/.eslintignore drupal-8.0.6/.eslintrc drupal-8.0.6/.gitattributes /var/www/drupal
    - name: Creamos directorio de trabajo de drupal
      shell: mkdir /var/www/drupal/sites/default/files
    - name: Cambiamos los permisos
      shell: chmod 0777 /var/www/drupal/sites
    - name: Creamos el settings.php 
      shell: cp /var/www/drupal/sites/default/default.settings.php /var/www/drupal/sites/default/settings.php
    - name: Y cambiamos los permisos
      shell: chmod 0777 /var/www/drupal/sites/default/settings.php
